#!/bin/bash
#version_1.0_Alpha

# Add some colours
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'
reset='\033[0m'


ask() {
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question
        [[ $1 == "i" ]] && msg=" ${yellow} ⃝¡ "
        [[ $1 == "w" ]] && msg=" ${yesgw} ⃝? "

        printf "${msg}${blue}"
        read -p "$3 [$prompt] " REPLY

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        printf "${reset}\n\n"
        # Check if the reply is valid
        case "$REPLY" in
        Y* | y*) [[ $4 == "r" ]] && return 1 || return 0 ;;
        N* | n*) [[ $4 == "r" ]] && return 0 || return 1 ;;
        esac
    done
}

tell () {
    [[ $1 == "d" ]] && mgs="${yellow} >>${light_cyan} "
    [[ $1 == "i" ]] && mgs="${yellow}  ⃝¡${blue} "
    [[ $1 == "s" ]] && mgs="${green} ✓⃝${light_cyan} "
    [[ $1 == "f" ]] && mgs="${red} ✗⃝ ${red} "
    printf "${mgs} ${2} ${reset}\n\n"
}

input (){
    [[ $1 == "d" ]] && mgs="${yellow} >>${light_cyan} "
    [[ $1 == "i" ]] && mgs="${yellow}  ⃝¡${blue} "
    [[ $1 == "s" ]] && mgs="${green}  ✓⃝${light_cyan} "
    [[ $1 == "f" ]] && mgs="${red} ✗⃝ ${red} "
    printf "${mgs} "
    read -p "$2" $3
    printf "${reset}\n\n"
    
}